name: Build ISOs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-iso-from-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download v3.0.0 ISO
        run: |
          wget https://github.com/pandalov3/bazzitegpdwin2/releases/download/v3.0.0/v3.0.0.iso -P ${{ github.workspace }}

      - name: Move ISO to Upload Directory
        run: |
          ISO_UPLOAD_DIR=${{ github.workspace }}/upload
          mkdir -p $ISO_UPLOAD_DIR
          mv ${{ github.workspace }}/v3.0.0.iso $ISO_UPLOAD_DIR
          echo "iso-upload-dir=${ISO_UPLOAD_DIR}" >> $GITHUB_ENV

      - name: Upload ISO to Job Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: v3.0.0.iso
          path: ${{ github.workspace }}/upload

